# Generated by Django 5.0.4 on 2024-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('price', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
